#!/bin/bash
sudo apt update -y
sudo apt install -y ansible
sudo apt install -y python3 python-is-python3 pip
sudo apt install python3-boto3 python3-botocore python3-boto -y
pip install ansible-core
pip install resolvelib
ansible-galaxy collection install community.general 
ansible-galaxy collection install amazon.aws

