#!/bin/bash
sudo apt update -y
sudo apt install -y ansible
sudo apt install -y python3 python-is-python3 pip
sudo apt install python3-boto3 python3-botocore python3-boto -y
pip install ansible-core
pip install -Iv 'resolvelib<0.6.0'
ansible-galaxy collection install community.general -y

